// Braid user-flow data: personas -> workflows -> cards (cards are listed in journey order).
// Each card: label (must start with "Screen n -" or "Notification n -"), desc, img (null = no screenshot yet).

const PERSONAS = [
  {
    num: "1",
    role: "User",
    navLabel: "User",
    workflows: [
      {
        code: "WF 01",
        title: "Public Landing & Data Discovery",
        cards: [
          { label: "Screen 1 - Home Page - Platform Landing", desc: "User lands on the public home page (before login) and sees the top navigation and the synthetic-data banner.", img: "img/p1_wf01_01.png" },
          { label: "Notification 1 - Modal - “Please Login to Continue”", desc: "Triggered on Screen 1 when a logged-out user opens a protected feature (Login / Cancel).", img: "img/p1_wf01_12.png" },
          { label: "Screen 2 - Home Page - Mission Statement (Scrolled View)", desc: "User scrolls to the mission statement, the CBR / BRAID mission copy and the Key Platform Features cards.", img: "img/p1_wf01_10.png" },
          { label: "Screen 3 - Explore Data - Guided Onboarding Steps", desc: "User follows the three onboarding steps (Explore Synthetic Data, Data Request, Access in No-Code Workspace) and reads the disclaimer.", img: "img/p1_wf01_09.png" },
          { label: "Screen 4 - Data Overview - Interactive Bubble Chart", desc: "User explores the radial bubble chart of cohorts and assessments; selecting an assessment reveals its subgroups.", img: "img/p1_wf01_08.png" },
          { label: "Screen 5 - Synthetic Data - Access Rules & Cohort Comparison", desc: "User clicks ’Explore Now’, reads the sandbox access rules and compares Cohort A and Cohort B.", img: "img/p1_wf01_02.png" },
          { label: "Screen 6 - Attribute Browsing (Grid / Table View)", desc: "User opens an assessment (e.g. Blood Biochemistry), filters by subgroup, searches and selects attributes. The ’N selected - View request’ bar appears.", img: "img/p1_wf01_03.png" },
          { label: "Screen 7 - Request for Attributes - Selected Attributes Review", desc: "User clicks ’View request’ to review the selected attributes, filters by dataset and can remove an attribute (Remove Attribute confirmation).", img: "img/p1_wf01_04.png" },
          { label: "Notification 2 - Modal - “Request submitted successfully!”", desc: "Triggered on Screen 5 after the synthetic data request is sent. Shows temporary credentials that expire in 30 minutes.", img: "img/p1_wf01_13.png" },
          { label: "Screen 8 - Synthetic Data - Session Bar with Temporary Credentials", desc: "After the request is sent, Synthetic Data opens in View Only mode. A session bar shows the time left, the temporary Email ID and Password (copy icons) and an ’Explore No Code’ button.", img: "img/p1_wf01_05.png" },
          { label: "Screen 9 - Login - Pre-filled with Temporary Credentials", desc: "User selects ’Open No-code Workspace’ and the Login screen opens pre-filled with the temporary Email ID and Password.", img: "img/p1_wf01_06.png" },
          { label: "Screen 10 - No-Code Workspace - Data Pipeline Builder (Temporary User)", desc: "After login the Data Pipeline Builder opens with the temporary user shown top right. A starter node (wide_export) asks for the required Name and Use Case; the Components panel lists Nodes and Templates.", img: "img/p1_wf01_07.png" },
          { label: "Screen 11 - Home Page - Return to Landing", desc: "Flow returns to the landing page. The profile menu offers Profile, Support and Log Out; Log Out redirects to the landing page.", img: "img/p1_wf01_11.png" },
        ],
      },
      {
        code: "WF 02",
        title: "User Login & Registration",
        cards: [
          { label: "Screen 1 - Login", desc: "User signs in with Email ID and Password (show / hide password, Forgot Password, Log In). Keycloak manages authentication.", img: "img/p1_wf02_01.png" },
          { label: "Notification 1 - Inline Error - “Invalid username or password”", desc: "Triggered on Screen 1 when the Email ID or password is incorrect; the banner and field are highlighted in red.", img: "img/p1_wf02_10.png" },
          { label: "Notification 2 - Inline Error - “Account is temporarily disabled”", desc: "Triggered on Screen 1 after 4-5 consecutive incorrect password attempts.", img: "img/p1_wf02_16.png" },
          { label: "Screen 2 - Register", desc: "New user opens Register. All fields except Email ID stay disabled until the email is verified.", img: "img/p1_wf02_02.png" },
          { label: "Notification 3 - Restriction - Organisation email domain check", desc: "Triggered on Screen 2: personal domains such as gmail.com are rejected and registration cannot proceed.", img: "img/p1_wf02_17.png" },
          { label: "Notification 4 - Toast - “Verification code sent”", desc: "Triggered on Screen 2 when the verification code is emailed to the user.", img: "img/p1_wf02_08.png" },
          { label: "Notification 5 - Email - “Email Verification” (OTP)", desc: "Sent after Screen 2 when the user clicks Verify: carries the 6-digit OTP, valid for 120 seconds.", img: "img/p1_wf02_11.png" },
          { label: "Screen 3 - Verify Your Email", desc: "User enters the 6-digit code within the 2-minute countdown, or clicks ’Resend OTP’.", img: "img/p1_wf02_03.png" },
          { label: "Notification 6 - Toast - “Incorrect code. Please check and try again.”", desc: "Triggered on Screen 3 when the entered code does not match the OTP.", img: "img/p1_wf02_12.png" },
          { label: "Screen 4 - Email Verified Successfully", desc: "After the correct code is entered, ’Email verified successfully!’ appears and the Email ID field shows a Verified badge. User clicks ’Ok, got it’ and completes the remaining fields.", img: "img/p1_wf02_04.png" },
          { label: "Notification 7 - Toast - “Email verified”", desc: "Triggered on Screen 4 as soon as the code is accepted.", img: "img/p1_wf02_13.png" },
          { label: "Screen 5 - Forgot Password - Reset Password", desc: "User clicks ’Forgot Password?’ on Login, lands on Reset password, enters the registered Email and clicks Submit.", img: "img/p1_wf02_05.png" },
          { label: "Notification 8 - Inline Message - “You should receive an email shortly with further instructions”", desc: "Triggered on Screen 5 after Submit: user returns to Login with a green confirmation banner.", img: "img/p1_wf02_14.png" },
          { label: "Notification 9 - Email - “Reset Password”", desc: "Sent after Screen 5: a Reset Password button; the link expires within 5 minutes.", img: "img/p1_wf02_15.png" },
          { label: "Screen 6 - Update Password", desc: "From the link in the reset email, user opens Update password, enters the New and Confirm Password and clicks Submit.", img: "img/p1_wf02_06.png" },
        ],
      },
      {
        code: "WF 03",
        title: "Authenticated Dataset Selection",
        cards: [
          { label: "Screen 1 - Dataset Information Table (Cohorts) - Authenticated View", desc: "Logged-in user compares the SANSCOG / TLSA cohorts (Attribute, Subject and Visits counts per assessment) and clicks ’Save & Explore’.", img: "img/p1_wf03_01.png" },
        ],
      },
      {
        code: "WF 04",
        title: "Data Access Request Submission",
        cards: [
          { label: "Screen 1 - Attribute Browsing (Grid / Table View)", desc: "User browses attributes by subgroup, switches Grid / Table view and multi-selects attributes. The ’N selected - View request’ bar appears.", img: "img/p1_wf04_01.png" },
          { label: "Screen 2 - Request for Attributes - Submit Access Request", desc: "User fills Request Name, Access Duration and Research Proposal Title, uploads the required PDF (<1 MB) and clicks ’Confirm & Send Request’.", img: "img/p1_wf04_02.png" },
          { label: "Notification 1 - Toast - “Request sent successfully”", desc: "Triggered on Screen 2 after ’Confirm & Send Request’.", img: "img/p1_wf04_06.png" },
          { label: "Screen 3 - Attribute Browsing - Leave Page Confirmation", desc: "If the user navigates away with attributes selected but not submitted, a ’Leave this page?’ prompt appears (Stay here / Leave & clear).", img: "img/p1_wf04_03.png" },
          { label: "Notification 2 - Modal - “Leave this page?”", desc: "Triggered on Screen 3: ’Leaving will clear all N selected attributes.’", img: "img/p1_wf04_07.png" },
          { label: "Screen 4 - Data Request Management - Tracking Requests", desc: "User tracks requests via the Total / Pending / Approved / Rejected tiles and the Pending, Approved, Renew and Rejected tables.", img: "img/p1_wf04_04.png" },
          { label: "Notification 3 - Toast - “Request ID copied to clipboard”", desc: "Triggered on Screen 4 after clicking the copy icon next to the Request ID.", img: "img/p1_wf04_08.png" },
          { label: "Screen 5 - Preview Manage Dataset Request", desc: "User clicks Preview to see the read-only request details and the Selected Attributes table.", img: "img/p1_wf04_05.png" },
        ],
      },
      {
        code: "WF 05",
        title: "Concept Graph Exploration",
        cards: [
          { label: "Screen 1 - Graph Explorer - Landing", desc: "User opens Graph Explorer, selects a cohort (SANSCOG / TLSA) and follows the five-step welcome guide.", img: "img/p1_wf05_01.png" },
          { label: "Screen 2 - Graph Explorer - Building the Concept Graph", desc: "Selected data is drawn as a concept graph. User switches Organic / Tree layouts, searches nodes, uses Share view or Export to JSON.", img: "img/p1_wf05_02.png" },
          { label: "Notification 1 - Confirmation - “Link copied”", desc: "Triggered on Screen 2 after clicking Share view.", img: "img/p1_wf05_09.png" },
          { label: "Screen 3 - Graph Explorer - Drilling into a Subgroup", desc: "User selects a subgroup to expand its related concepts while the parent dataset node stays visible; hover shows node name and connections.", img: "img/p1_wf05_03.png" },
          { label: "Screen 4 - Graph Explorer - Node Legend", desc: "User opens the Legend to read the node colour coding (Cohort, Dataset, Subgroup, CBR concept, SNOMED, Already requested ...).", img: "img/p1_wf05_04.png" },
          { label: "Screen 5 - Graph Explorer - Node Context Menu", desc: "Selecting a node shows ’Request access to dataset / subgroup’ and ’Isolate this branch’. Isolating adds a removable ’Isolated: <node>’ chip.", img: "img/p1_wf05_05.png" },
          { label: "Screen 6 - Graph Explorer - Fully Expanded Concept Fan-Out", desc: "Expanded view shows the dense concept tree. Sidebar counters and the Requested Concepts badge update live.", img: "img/p1_wf05_06.png" },
          { label: "Screen 7 - Requested Concepts Tracker", desc: "User opens Requested Concepts: requests grouped as Approved / Pending (status badges), expandable per request, with a ’Remove request’ action.", img: "img/p1_wf05_07.png" },
          { label: "Screen 8 - Request for Access - Concept / Subgroup", desc: "User sets Access Duration and Use Cases, uploads the required PDF, reviews the Selected Items and clicks Confirm.", img: "img/p1_wf05_08.png" },
          { label: "Notification 2 - Toast - “Request submitted”", desc: "Triggered on Screen 8: confirmation shown on the graph canvas after Confirm.", img: "img/p1_wf05_10.png" },
        ],
      },
      {
        code: "WF 06",
        title: "Approved Request to Code Workspace",
        cards: [
          { label: "Screen 1 - Data Request Management - Workspace Entry Point", desc: "User opens Approved Data Requests, which gives the No-Code entry link (’Click here’) and the Code workspace route.", img: "img/p1_wf06_01.png" },
          { label: "Screen 2 - Workspace - Create Workspace (Empty State)", desc: "Workspace section lets the user create a Code workspace (up to one CPU and one GPU workspace).", img: "img/p1_wf06_02.png" },
          { label: "Notification 1 - Restriction - “Cannot create a new workspace”", desc: "Triggered on Screen 2: a new workspace cannot be created while another is running; stop the existing one first.", img: "img/p1_wf06_10.png" },
          { label: "Screen 3 - Create Workspace - New Workspace Modal", desc: "User enters a Workspace Name, picks CPU / GPU and accepts the policy terms.", img: "img/p1_wf06_03.png" },
          { label: "Screen 4 - Create Workspace - Form Validated & Instance Details", desc: "Naming rules are validated (4-30 chars, lowercase, hyphen rules) and the instance resources (e.g. Memory 1GB, Disk 10GB) are shown.", img: "img/p1_wf06_04.png" },
          { label: "Screen 5 - Workspace - Created Successfully (Provisioning)", desc: "New workspace appears with Type, Status (opening) and Created On; the remaining workspace allowance updates.", img: "img/p1_wf06_05.png" },
          { label: "Notification 2 - Toast - “Workspace created successfully!”", desc: "Triggered on Screen 5 immediately after Create Workspace.", img: "img/p1_wf06_11.png" },
          { label: "Screen 6 - Workspace - Running Code Workspace", desc: "Status changes from opening to running. Opening the workspace launches JupyterLab.", img: "img/p1_wf06_06.png" },
          { label: "Screen 7 - Workspace - “Notebook is Ready”", desc: "User clicks Open on the running workspace card. A ’Notebook is Ready’ prompt (Cancel / Okay) appears before JupyterLab opens in a new page.", img: "img/p1_wf06_07.png" },
          { label: "Notification 3 - Modal - “Notebook is Ready”", desc: "Triggered on Screen 7: ’Your Notebook is now Running and ready to use. Click Okay to open it in a new page.’", img: "img/p1_wf06_12.png" },
          { label: "Screen 8 - Workspace - Open / Stop an Existing Workspace", desc: "The workspace card’s menu offers Open and Stop. Stop ends the running session.", img: "img/p1_wf06_08.png" },
          { label: "Notification 4 - Toast - “Workspace stopped successfully.”", desc: "Triggered on Screen 8 after selecting Stop from the workspace card menu.", img: "img/p1_wf06_13.png" },
          { label: "Screen 9 - Code Workspace - JupyterLab (CBR Data Access Starter)", desc: "JupyterLab opens with starter notebooks, SDK documentation and guides for accessing the approved data.", img: "img/p1_wf06_09.png" },
        ],
      },
      {
        code: "WF 07",
        title: "No-Code Pipeline Builder",
        cards: [
          { label: "Screen 1 - No-Code Pipeline Builder - Guided Component Tour", desc: "No-Code builder opens with a starter node tied to the approved request. A 12-step guided tour explains components, pipeline building and execution.", img: "img/p1_wf07_01.png" },
          { label: "Screen 2 - No-Code Pipeline Builder - Pipeline Rules", desc: "User opens the (i) icon to read Node Requirements, Connections and Execution & Artifacts rules.", img: "img/p1_wf07_02.png" },
          { label: "Screen 3 - No-Code Pipeline Builder - Node Configuration Panel", desc: "User fills the required Name and Use Case, then uses Help Me Start, Save as Template, Clear, Executions, Save or Execute.", img: "img/p1_wf07_03.png" },
          { label: "Screen 4 - No-Code Pipeline Builder - Save as Template", desc: "User names the template, adds a description, icon and accent colour, and clicks ’Save template’.", img: "img/p1_wf07_04.png" },
          { label: "Screen 5 - No-Code Pipeline Builder - Pipeline Executions Panel", desc: "User opens Executions to see past runs, or the ’No executions yet’ empty state.", img: "img/p1_wf07_05.png" },
          { label: "Screen 6 - No-Code Pipeline Builder - Connecting Pipeline Nodes", desc: "User connects nodes (e.g. wide_export to sql_transformer). Leaving with unsaved changes opens ’Unsaved Changes’ (Stay / Discard Changes / Save & Continue).", img: "img/p1_wf07_06.png" },
          { label: "Notification 1 - Toast - “Pipeline updated successfully!”", desc: "Triggered after the pipeline is saved.", img: "img/p1_wf07_11.png" },
          { label: "Screen 7 - No-Code Pipeline Builder - Execution & Live Monitoring", desc: "User clicks Execute. The Execution view shows Running status and live node progress; Cancel can stop it.", img: "img/p1_wf07_07.png" },
          { label: "Notification 2 - Panel (red) - “Validation Errors”", desc: "Triggered on Screen 7 when validation fails (e.g. a missing required field or disconnected pipelines).", img: "img/p1_wf07_09.png" },
          { label: "Notification 3 - Confirmation - “Pipeline saved and execution started”", desc: "Triggered on Screen 7 once validation passes and the run begins.", img: "img/p1_wf07_10.png" },
          { label: "Screen 8 - Custom Nodes", desc: "User registers custom transformation nodes via Add Node (0 registered by default; Refresh available).", img: "img/p1_wf07_08.png" },
        ],
      },
      {
        code: "WF 08",
        title: "Managing the User Account",
        cards: [
          { label: "Screen 1 - My Profile", desc: "User opens My Profile to see account details (name, email with Verified badge, affiliation, designation, phone, portfolio URL), with an Edit action.", img: "img/p1_wf08_01.png" },
          { label: "Screen 2 - Change Password", desc: "User clicks ’Change Password’ to update the password used to sign in.", img: "img/p1_wf08_02.png" },
          { label: "Screen 3 - Agreements", desc: "User views the Privacy Policy and Terms of Service accepted at registration.", img: "img/p1_wf08_03.png" },
          { label: "Screen 4 - Delete Account", desc: "User reads the ’no going back’ warning and clicks ’Delete My Account’.", img: "img/p1_wf08_04.png" },
          { label: "Screen 5 - Delete Account - Confirmation", desc: "A ’This Action Will Permanently Delete Your Account’ prompt appears. User clicks ’Delete Account’ or Cancel.", img: "img/p1_wf08_05.png" },
          { label: "Notification 1 - Modal - “Are you sure you want to delete your account?”", desc: "Triggered on Screen 5: the user has a 7-day grace period to download results.", img: "img/p1_wf08_06.png" },
          { label: "Notification 5 - Toast - “Account deletion scheduled”", desc: "Triggered on Screen 5 after ’Delete Account’ is confirmed: the account stays usable for the next 7 days and is then permanently deleted.", img: "img/p1_wf08_07.png" },
          { label: "Notification 2 - Email - “Account Deletion Requested”", desc: "Sent after Screen 5: confirms the 7-day grace period has started and the account cannot be restored during it.", img: "img/p1_wf08_08.png" },
          { label: "Notification 3 - Email - “Account Permanently Deleted”", desc: "System-triggered when the 7-day grace period ends. No in-app screen.", img: "img/p1_wf08_09.png" },
          { label: "Notification 4 - Email - “Suspicious activity detected”", desc: "Admin-triggered: access is revoked immediately with no grace period. No in-app screen.", img: "img/p1_wf08_10.png" },
        ],
      },
      {
        code: "WF 09",
        title: "Help, About & Accessibility",
        cards: [
          { label: "Screen 1 - About CBR", desc: "User opens About Us: CBR at a Glance, Our Mandate, BRAID as Digital Public Infrastructure and Key Platform Features.", img: "img/p1_wf09_01.png" },
          { label: "Screen 2 - Frequently Asked Questions", desc: "User opens the FAQ and expands a question (What is BRAID, Who can use BRAID, What is Synthetic Data ...).", img: "img/p1_wf09_02.png" },
          { label: "Screen 3 - Support Center", desc: "User opens Support: ’Get help and find resources’ with FAQ, User Manual and Help & Support cards.", img: "img/p1_wf09_03.png" },
          { label: "Screen 4 - Accessibility Options", desc: "User opens the accessibility panel: text size, greyscale, contrast modes, readable font and Reset.", img: "img/p1_wf09_04.png" },
        ],
      },
    ],
  },
  {
    num: "2",
    role: "User (No Access to Data Request)",
    navLabel: "User (No Data Request)",
    workflows: [
      {
        code: "WF 01",
        title: "Restricted Navigation (Organisation Data Access Disabled)",
        cards: [
          { label: "Screen 1 - Top Navigation - Reduced Menu", desc: "User signs in. The top navigation shows only About Us, Datasets and Workspace; the name and Logout sit inline next to the avatar.", img: "img/p2_wf01_01.png" },
        ],
      },
      {
        code: "WF 02",
        title: "Concept Graph Exploration (Organisation Data Access Disabled)",
        cards: [
          { label: "Screen 1 - Graph Explorer - Reached via Share View Link", desc: "Graph Explorer has no nav link for this role, so the user reaches it through a Share view link. Cohorts, graph, Legend and the Isolated filter work as usual.", img: "img/p2_wf02_01.png" },
        ],
      },
    ],
  },
  {
    num: "3",
    role: "Admin",
    navLabel: "Admin",
    workflows: [
      {
        code: "WF 01",
        title: "System Oversight",
        cards: [
          { label: "Screen 1 - Admin Dashboard - System Oversight & Organisation Directory", desc: "Admin enters the Admin Panel and sees six System Oversight tiles and the Organisation table with Add New, Edit and Delete.", img: "img/p3_wf01_01.png" },
        ],
      },
      {
        code: "WF 02",
        title: "Organisation Management",
        cards: [
          { label: "Screen 1 - Add New Organisation", desc: "Admin clicks Add New, enters Organisation Name, Official Email Domain and Internal Notes, ticks ’Allow Data Request’ and clicks ’Add Organisation’.", img: "img/p3_wf02_01.png" },
          { label: "Notification 1 - Toast - “Organisation created successfully”", desc: "Triggered on Screen 1 after Add Organisation; the new row appears at the top of the table.", img: "img/p3_wf02_04.png" },
          { label: "Screen 2 - Edit Organisation", desc: "Admin clicks the row edit icon, changes a field (e.g. Official Email Domain) and clicks Save.", img: "img/p3_wf02_02.png" },
          { label: "Notification 2 - Toast - “No changes were made”", desc: "Triggered on Screen 2 when Save is clicked without editing any field.", img: "img/p3_wf02_05.png" },
          { label: "Notification 3 - Toast - “Organisation updated successfully”", desc: "Triggered on Screen 2 when Save is clicked after a field has changed.", img: "img/p3_wf02_06.png" },
          { label: "Screen 3 - Delete Organisation", desc: "Admin clicks the row delete icon and confirms ’Delete’ in the confirmation prompt.", img: "img/p3_wf02_03.png" },
          { label: "Notification 4 - Toast - “Organisation deleted successfully”", desc: "Triggered on Screen 3 after confirming Delete; the row is removed.", img: "img/p3_wf02_07.png" },
        ],
      },
      {
        code: "WF 03",
        title: "Role Assignment Management",
        cards: [
          { label: "Screen 1 - Role Assignment - Assigned Roles Table", desc: "Admin scrolls to Role Assignment: users holding an admin-side role, with Add New and per-row Edit / Delete.", img: "img/p3_wf03_01.png" },
          { label: "Notification 1 - Toast - “User role rolled back successfully”", desc: "Triggered on Screen 1 when a user role is rolled back.", img: "img/p3_wf03_04.png" },
          { label: "Screen 2 - Add New User Role", desc: "Admin enters an email and clicks Check. Once verified the name auto-fills and the role boxes (User Manager, Data Request Manager) unlock; clicks ’Add Role’.", img: "img/p3_wf03_02.png" },
          { label: "Notification 2 - Inline Error - “User not found”", desc: "Triggered on Screen 2 when Check finds no matching account; Add Role stays disabled.", img: "img/p3_wf03_05.png" },
          { label: "Screen 3 - Edit User Role", desc: "Admin clicks the row edit icon, adjusts the role checkboxes and clicks Save.", img: "img/p3_wf03_03.png" },
          { label: "Notification 3 - Toast - “No changes were made”", desc: "Triggered on Screen 3 when Save is clicked without changing the role selection.", img: "img/p3_wf03_06.png" },
          { label: "Notification 4 - Toast - “User role upgraded successfully”", desc: "Triggered on Screen 3 when Save is clicked after adding a role.", img: "img/p3_wf03_07.png" },
        ],
      },
      {
        code: "WF 04",
        title: "Admin Account & Profile",
        cards: [
          { label: "Screen 1 - My Profile - Account Information", desc: "Admin opens My Profile from the avatar menu and sees the read-only Account Information with an Edit action.", img: "img/p3_wf04_01.png" },
          { label: "Screen 2 - My Profile - Edit Account Information", desc: "Admin clicks Edit, updates the details and saves.", img: "img/p3_wf04_02.png" },
          { label: "Notification 1 - Toast - “Profile updated successfully”", desc: "Triggered on Screen 2 after saving the edited profile details.", img: "img/p3_wf04_06.png" },
          { label: "Screen 3 - Re-authenticate to Continue", desc: "Clicking ’Change Password’ asks the admin to re-enter Email ID and Password.", img: "img/p3_wf04_03.png" },
          { label: "Screen 4 - Update Password", desc: "Admin enters New / Confirm Password against the live rule checklist, keeps ’Sign out from other devices’ ticked and clicks Submit.", img: "img/p3_wf04_04.png" },
          { label: "Notification 2 - Toast - “Password changed successfully”", desc: "Triggered on Screen 4 after Submit; the admin returns to My Profile and is logged out shortly.", img: "img/p3_wf04_07.png" },
          { label: "Screen 5 - Profile Menu (Avatar Dropdown)", desc: "The top-right avatar dropdown offers Profile, Support and Logout.", img: "img/p3_wf04_05.png" },
        ],
      },
    ],
  },
  {
    num: "4",
    role: "Data Request Manager",
    navLabel: "Data Request Manager",
    workflows: [
      {
        code: "WF 01",
        title: "Data Request Management - Pending Requests",
        cards: [
          { label: "Screen 1 - Pending Data Requests", desc: "Manager opens Data request management and sees the Pending Data Requests table with a Datasets filter (All / SANSCOG / TLSA).", img: "img/p4_wf01_01.png" },
          { label: "Notification 1 - Toast - “Request ID copied to clipboard”", desc: "Triggered on Screen 1 after clicking the copy icon next to the Request ID.", img: "img/p4_wf01_05.png" },
          { label: "Screen 2 - Manage Dataset Request", desc: "Manager clicks the row edit icon, reviews the request and document, and picks Accept or Reject (Reject needs a reason). Clicks Confirm.", img: "img/p4_wf01_02.png" },
          { label: "Screen 3 - Document Preview (PDF Viewer)", desc: "Manager clicks the eye icon beside the attached document to read the uploaded PDF.", img: "img/p4_wf01_03.png" },
          { label: "Screen 4 - Confirm Rejection?", desc: "After Confirm with Reject selected: ’Are you sure you want to reject this data request?’", img: "img/p4_wf01_04.png" },
          { label: "Notification 2 - Toast - “Data request rejected successfully.”", desc: "Triggered on Screen 4 after confirming Reject; the row leaves the Pending table.", img: "img/p4_wf01_06.png" },
        ],
      },
      {
        code: "WF 02",
        title: "Data Request Management - Renew Data Request",
        cards: [
          { label: "Screen 1 - Renew Data Request - Pending", desc: "Manager scrolls to the Renew Data Request (Pending) table of extension requests.", img: "img/p4_wf02_01.png" },
          { label: "Screen 2 - Manage Renewal Request", desc: "Manager clicks edit: sees Attribute Count, Expired On, applicant details, document and Requested Attributes, then picks Accept or Reject (reason required).", img: "img/p4_wf02_02.png" },
          { label: "Screen 3 - Confirm Renewal Rejection?", desc: "After Confirm with Reject selected: ’Are you sure you want to reject this renewal request?’", img: "img/p4_wf02_03.png" },
          { label: "Notification 1 - Toast - “Extension request rejected successfully.”", desc: "Triggered on Screen 3 after confirming Reject; the row leaves the Renew (Pending) table.", img: "img/Extend_request.png" },
          { label: "Screen 4 - Confirm Renewal Acceptance?", desc: "After Confirm with Accept selected: ’Are you sure you want to accept this renewal request?’", img: "img/p4_wf02_04.png" },
          { label: "Notification 2 - Toast - “Extension request approved successfully.”", desc: "Triggered on Screen 4 after confirming Accept; the row leaves the Renew (Pending) table.", img: "img/p4_wf02_06.png" },
        ],
      },
      {
        code: "WF 03",
        title: "Data Request Management - Approved Data Requests",
        cards: [
          { label: "Screen 1 - Approved Data Requests", desc: "Manager views every approved request (Data Request / Synthetic Data Request tabs) with a Datasets filter and a Preview eye icon.", img: "img/p4_wf03_01.png" },
        ],
      },
    ],
  },
  {
    num: "5",
    role: "User Manager",
    navLabel: "User Manager",
    workflows: [
      {
        code: "WF 01",
        title: "User Management - Pending Requests",
        cards: [
          { label: "Screen 1 - User Management - Pending Requests", desc: "Manager opens User management and sees the Pending Requests table with Date Range and Affiliation filters (CBR, Datakaveri, SIRPI, TANUH).", img: "img/p5_wf01_01.png" },
          { label: "Screen 2 - Manage User Request", desc: "Manager clicks the row edit icon, reviews applicant, email, requested date and reason for joining, then picks Accept or Reject (reason required).", img: "img/p5_wf01_02.png" },
          { label: "Screen 3 - Confirm Acceptance?", desc: "After Confirm with Accept selected: ’Are you sure you want to accept this user request?’", img: "img/p5_wf01_03.png" },
          { label: "Notification 1 - Toast - “Request approved successfully.”", desc: "Triggered on Screen 3 after confirming Accept; the row moves to Registered Requests.", img: "img/p5_wf01_05.png" },
          { label: "Screen 4 - Confirm Rejection?", desc: "After Confirm with Reject selected: ’Are you sure you want to reject this user request?’", img: "img/p5_wf01_04.png" },
          { label: "Notification 2 - Toast - “Request rejected successfully.”", desc: "Triggered on Screen 4 after confirming Reject; the row moves to Rejected Requests.", img: "img/p5_wf01_06.png" },
        ],
      },
      {
        code: "WF 02",
        title: "User Management - Registered Requests",
        cards: [
          { label: "Screen 1 - User Management - Registered Requests", desc: "Manager views every approved user with filters, pagination, a Preview (eye) icon and a delete icon.", img: "img/p5_wf02_01.png" },
          { label: "Screen 2 - Registered Users (Preview)", desc: "Read-only preview: applicant, email, submission date, approved by / date and reason for joining.", img: "img/p5_wf02_02.png" },
          { label: "Screen 3 - Delete User?", desc: "The delete icon opens: ’Are you sure you want to permanently delete this user?’", img: "img/p5_wf02_03.png" },
          { label: "Notification 1 - Toast - “User deleted successfully.”", desc: "Triggered on Screen 3 after confirming Delete; the row is removed from Registered Requests.", img: "img/p5_wf02_04.png" },
        ],
      },
      {
        code: "WF 03",
        title: "User Management - Rejected Requests",
        cards: [
          { label: "Screen 1 - User Management - Rejected Requests", desc: "Manager views every rejected application with filters. Only a Preview (eye) action is available; there is no delete.", img: "img/p5_wf03_01.png" },
          { label: "Screen 2 - Rejected Users (Preview)", desc: "Read-only preview: applicant, email, submission date, rejected by / date and reason.", img: "img/p5_wf03_02.png" },
        ],
      },
    ],
  },
];
